
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, Checkbutton, IntVar, Radiobutton



def print_entries():
    # Pobierz wartości wpisane do pól Entry
    m_row = entry_1.get()
    n_colls = entry_59.get()
    square_size = 60
    square_size = min(522 / int(m_row), 480 / int(n_colls))
    board_preview = BoardPreview(window, int(m_row), int(n_colls), square_size, 'white')
    board_preview.place(x = 628, y = 25)
    # 1150 508
    # n_of_a_value = entry_2.get()
    # n_of_d_value = entry_3.get()
    # n_of_b_value = entry_5.get()
    # n_of_iter_value = entry_6.get()
    # n_of_exper_value = entry_4.get()

    # Wydrukuj wartości w konsoli
    print("M_row:", m_row)
    print("N_colls:", n_colls)
    # print("n_of_A:", n_of_a_value)
    # print("n_of_D:", n_of_d_value)
    # print("n_of_B:", n_of_b_value)
    # print("n_of_iter:", n_of_iter_value)
    # print("n_of_exper:", n_of_exper_value)

class BoardPreview(Canvas):
    def __init__(self, master, rows, columns, square_size, color):
        super().__init__(master, width=columns * square_size, height=rows * square_size)
        self.rows = rows
        self.columns = columns
        self.square_size = square_size
        self.color = color
        self.draw_board()

    def draw_board(self):
        for row in range(self.rows):
            for col in range(self.columns):
                x0 = col * self.square_size
                y0 = row * self.square_size
                x1 = x0 + self.square_size
                y1 = y0 + self.square_size
                color = self.color
                self.create_rectangle(x0, y0, x1, y1, fill=color, outline='black')

# Przykładowe kolory planszy
board_colors = [
    ['red', 'green', 'blue'],
    ['yellow', 'orange', 'purple'],
    ['cyan', 'magenta', 'brown']
]



OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\xiii5\Desktop\Notatki_stacja\UKSW\selected AI\test\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1200x850")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 850,
    width = 1200,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    4.0,
    4.0,
    5.0,
    845.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    4.0,
    4.0,
    600.0,
    5.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    4.0,
    843.9999999999998,
    600.0,
    845.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    599.0,
    843.9999999999998,
    1194.0,
    845.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    599.0,
    3.9999999999998295,
    1194.0,
    5.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    599.0,
    4.0,
    600.0,
    845.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    1193.0,
    4.0,
    1194.0,
    845.0,
    fill="#000000",
    outline="")

canvas.create_text(
    20.0,
    50.0,
    anchor="nw",
    text="N_colls",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    20.0,
    88.0,
    anchor="nw",
    text="n_of_A",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    20.0,
    108.0,
    anchor="nw",
    text="n_of_D",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    20.0,
    128.0,
    anchor="nw",
    text="n_of_B",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    20.0,
    166.0,
    anchor="nw",
    text="n_of_iter",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    20.0,
    186.0,
    anchor="nw",
    text="n_of_exper",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    20.0,
    30.0,
    anchor="nw",
    text="M_row",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    135.0,
    245.0,
    anchor="nw",
    text="min",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    268.0,
    245.0,
    anchor="nw",
    text="max",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    20.0,
    225.0,
    anchor="nw",
    text="Parameters of A",
    fill="#000000",
    font=("Inter Bold", 16 * -1)
)

canvas.create_text(
    20.0,
    412.0,
    anchor="nw",
    text="Risc_accept_level (IQ)",
    fill="#000000",
    font=("Inter Bold", 16 * -1)
)

canvas.create_text(
    21.0,
    579.0,
    anchor="nw",
    text="Mobility (IQ)",
    fill="#000000",
    font=("Inter Bold", 16 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    147.5,
    39.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=120.0,
    y=30.0,
    width=55.0,
    height=16.0
)

canvas.create_text(
    20.0,
    264.0,
    anchor="nw",
    text="IQ_range",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    20.0,
    294.0,
    anchor="nw",
    text="Health_state",
    fill="#000000",
    font=("Inter Bold", 16 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    147.5,
    273.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=120.0,
    y=264.0,
    width=55.0,
    height=16.0
)

canvas.create_text(
    20.0,
    380.0,
    anchor="nw",
    text="n_iter_susp_B",
    fill="#000000",
    font=("Inter", 14 * -1)
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    147.5,
    389.0,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=120.0,
    y=380.0,
    width=55.0,
    height=16.0
)

canvas.create_text(
    43.0,
    325.0,
    anchor="nw",
    text="p_HS1",
    fill="#000000",
    font=("Inter", 14 * -1)
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    147.5,
    335.0,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_4.place(
    x=120.0,
    y=326.0,
    width=55.0,
    height=16.0
)

canvas.create_text(
    217.0,
    325.0,
    anchor="nw",
    text="p_HS2",
    fill="#000000",
    font=("Inter", 14 * -1)
)

entry_image_5 = PhotoImage(
    file=relative_to_assets("entry_5.png"))
entry_bg_5 = canvas.create_image(
    321.5,
    335.0,
    image=entry_image_5
)
entry_5 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_5.place(
    x=294.0,
    y=326.0,
    width=55.0,
    height=16.0
)

canvas.create_text(
    408.0,
    325.0,
    anchor="nw",
    text="p_HS3",
    fill="#000000",
    font=("Inter", 14 * -1)
)

entry_image_6 = PhotoImage(
    file=relative_to_assets("entry_6.png"))
entry_bg_6 = canvas.create_image(
    512.5,
    335.0,
    image=entry_image_6
)
entry_6 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_6.place(
    x=485.0,
    y=326.0,
    width=55.0,
    height=16.0
)

canvas.create_text(
    47.0,
    490.0,
    anchor="nw",
    text="B1",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    130.0,
    470.0,
    anchor="nw",
    text="p_acc",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    140.0,
    599.0,
    anchor="nw",
    text="p_mob",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    26.0,
    786.0,
    anchor="nw",
    text="power",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    210.0,
    786.0,
    anchor="nw",
    text="fax",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    401.0,
    787.0,
    anchor="nw",
    text="???",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    156.0,
    583.0,
    anchor="nw",
    text="1",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    329.0,
    583.0,
    anchor="nw",
    text="2",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    501.0,
    583.0,
    anchor="nw",
    text="3",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    145.0,
    304.0,
    anchor="nw",
    text="1",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    318.0,
    304.0,
    anchor="nw",
    text="2",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    506.0,
    304.0,
    anchor="nw",
    text="3",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    309.0,
    599.0,
    anchor="nw",
    text="p_mob",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    481.0,
    599.0,
    anchor="nw",
    text="p_mob",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    498.0,
    470.0,
    anchor="nw",
    text="p_acc",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    306.0,
    470.0,
    anchor="nw",
    text="p_acc",
    fill="#000000",
    font=("Inter", 14 * -1)
)

entry_image_7 = PhotoImage(
    file=relative_to_assets("entry_7.png"))
entry_bg_7 = canvas.create_image(
    151.5,
    500.0,
    image=entry_image_7
)
entry_7 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_7.place(
    x=124.0,
    y=491.0,
    width=55.0,
    height=16.0
)

entry_image_8 = PhotoImage(
    file=relative_to_assets("entry_8.png"))
entry_bg_8 = canvas.create_image(
    325.5,
    500.0,
    image=entry_image_8
)
entry_8 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_8.place(
    x=298.0,
    y=491.0,
    width=55.0,
    height=16.0
)

entry_image_9 = PhotoImage(
    file=relative_to_assets("entry_9.png"))
entry_bg_9 = canvas.create_image(
    516.5,
    500.0,
    image=entry_image_9
)
entry_9 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_9.place(
    x=489.0,
    y=491.0,
    width=55.0,
    height=16.0
)

entry_image_10 = PhotoImage(
    file=relative_to_assets("entry_10.png"))
entry_bg_10 = canvas.create_image(
    48.5,
    816.0,
    image=entry_image_10
)
entry_10 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_10.place(
    x=21.0,
    y=807.0,
    width=55.0,
    height=16.0
)

entry_image_11 = PhotoImage(
    file=relative_to_assets("entry_11.png"))
entry_bg_11 = canvas.create_image(
    222.5,
    816.0,
    image=entry_image_11
)
entry_11 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_11.place(
    x=195.0,
    y=807.0,
    width=55.0,
    height=16.0
)

entry_image_12 = PhotoImage(
    file=relative_to_assets("entry_12.png"))
entry_bg_12 = canvas.create_image(
    413.5,
    816.0,
    image=entry_image_12
)
entry_12 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_12.place(
    x=386.0,
    y=807.0,
    width=55.0,
    height=16.0
)

canvas.create_text(
    47.0,
    518.0,
    anchor="nw",
    text="B2",
    fill="#000000",
    font=("Inter", 14 * -1)
)

entry_image_13 = PhotoImage(
    file=relative_to_assets("entry_13.png"))
entry_bg_13 = canvas.create_image(
    151.5,
    528.0,
    image=entry_image_13
)
entry_13 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_13.place(
    x=124.0,
    y=519.0,
    width=55.0,
    height=16.0
)

entry_image_14 = PhotoImage(
    file=relative_to_assets("entry_14.png"))
entry_bg_14 = canvas.create_image(
    325.5,
    528.0,
    image=entry_image_14
)
entry_14 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_14.place(
    x=298.0,
    y=519.0,
    width=55.0,
    height=16.0
)

entry_image_15 = PhotoImage(
    file=relative_to_assets("entry_15.png"))
entry_bg_15 = canvas.create_image(
    516.5,
    528.0,
    image=entry_image_15
)
entry_15 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_15.place(
    x=489.0,
    y=519.0,
    width=55.0,
    height=16.0
)

canvas.create_text(
    47.0,
    545.0,
    anchor="nw",
    text="B3",
    fill="#000000",
    font=("Inter", 14 * -1)
)

entry_image_16 = PhotoImage(
    file=relative_to_assets("entry_16.png"))
entry_bg_16 = canvas.create_image(
    151.5,
    555.0,
    image=entry_image_16
)
entry_16 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_16.place(
    x=124.0,
    y=546.0,
    width=55.0,
    height=16.0
)

entry_image_17 = PhotoImage(
    file=relative_to_assets("entry_17.png"))
entry_bg_17 = canvas.create_image(
    325.5,
    555.0,
    image=entry_image_17
)
entry_17 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_17.place(
    x=298.0,
    y=546.0,
    width=55.0,
    height=16.0
)

entry_image_18 = PhotoImage(
    file=relative_to_assets("entry_18.png"))
entry_bg_18 = canvas.create_image(
    516.5,
    555.0,
    image=entry_image_18
)
entry_18 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_18.place(
    x=489.0,
    y=546.0,
    width=55.0,
    height=16.0
)

entry_image_19 = PhotoImage(
    file=relative_to_assets("entry_19.png"))
entry_bg_19 = canvas.create_image(
    163.5,
    629.0,
    image=entry_image_19
)
entry_19 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_19.place(
    x=136.0,
    y=620.0,
    width=55.0,
    height=16.0
)

entry_image_20 = PhotoImage(
    file=relative_to_assets("entry_20.png"))
entry_bg_20 = canvas.create_image(
    333.5,
    629.0,
    image=entry_image_20
)
entry_20 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_20.place(
    x=306.0,
    y=620.0,
    width=55.0,
    height=16.0
)

entry_image_21 = PhotoImage(
    file=relative_to_assets("entry_21.png"))
entry_bg_21 = canvas.create_image(
    503.5,
    629.0,
    image=entry_image_21
)
entry_21 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_21.place(
    x=476.0,
    y=620.0,
    width=55.0,
    height=16.0
)

canvas.create_text(
    21.0,
    648.0,
    anchor="nw",
    text="Business type",
    fill="#000000",
    font=("Inter Bold", 16 * -1)
)

canvas.create_text(
    20.0,
    760.0,
    anchor="nw",
    text="Wealth thr",
    fill="#000000",
    font=("Inter Bold", 16 * -1)
)

canvas.create_text(
    21.0,
    689.0,
    anchor="nw",
    text="p_HS1",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    95.0,
    806.0,
    anchor="nw",
    text="of IC",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    269.0,
    806.0,
    anchor="nw",
    text="of IC",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    460.0,
    806.0,
    anchor="nw",
    text="of IC",
    fill="#000000",
    font=("Inter", 14 * -1)
)

entry_image_22 = PhotoImage(
    file=relative_to_assets("entry_22.png"))
entry_bg_22 = canvas.create_image(
    106.5,
    699.0,
    image=entry_image_22
)
entry_22 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_22.place(
    x=79.0,
    y=690.0,
    width=55.0,
    height=16.0
)

canvas.create_text(
    21.0,
    710.0,
    anchor="nw",
    text="p_HS1",
    fill="#000000",
    font=("Inter", 14 * -1)
)

entry_image_23 = PhotoImage(
    file=relative_to_assets("entry_23.png"))
entry_bg_23 = canvas.create_image(
    106.5,
    720.0,
    image=entry_image_23
)
entry_23 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_23.place(
    x=79.0,
    y=711.0,
    width=55.0,
    height=16.0
)

canvas.create_text(
    21.0,
    731.0,
    anchor="nw",
    text="p_HS1",
    fill="#000000",
    font=("Inter", 14 * -1)
)

entry_image_24 = PhotoImage(
    file=relative_to_assets("entry_24.png"))
entry_bg_24 = canvas.create_image(
    106.5,
    741.0,
    image=entry_image_24
)
entry_24 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_24.place(
    x=79.0,
    y=732.0,
    width=55.0,
    height=16.0
)

canvas.create_text(
    200.0,
    670.0,
    anchor="nw",
    text="inv a",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    136.0,
    689.0,
    anchor="nw",
    text="of IC",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    136.0,
    710.0,
    anchor="nw",
    text="of IC",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    495.0,
    688.0,
    anchor="nw",
    text="of IC",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    495.0,
    709.0,
    anchor="nw",
    text="of IC",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    136.0,
    731.0,
    anchor="nw",
    text="of IC",
    fill="#000000",
    font=("Inter", 14 * -1)
)

entry_image_25 = PhotoImage(
    file=relative_to_assets("entry_25.png"))
entry_bg_25 = canvas.create_image(
    216.5,
    699.0,
    image=entry_image_25
)
entry_25 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_25.place(
    x=189.0,
    y=690.0,
    width=55.0,
    height=16.0
)

entry_image_26 = PhotoImage(
    file=relative_to_assets("entry_26.png"))
entry_bg_26 = canvas.create_image(
    216.5,
    741.0,
    image=entry_image_26
)
entry_26 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_26.place(
    x=189.0,
    y=732.0,
    width=55.0,
    height=16.0
)

entry_image_27 = PhotoImage(
    file=relative_to_assets("entry_27.png"))
entry_bg_27 = canvas.create_image(
    216.5,
    720.0,
    image=entry_image_27
)
entry_27 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_27.place(
    x=189.0,
    y=711.0,
    width=55.0,
    height=16.0
)

canvas.create_text(
    263.0,
    656.0,
    anchor="nw",
    text="increase of GAP",
    fill="#000000",
    font=("Inter", 14 * -1)
)

entry_image_28 = PhotoImage(
    file=relative_to_assets("entry_28.png"))
entry_bg_28 = canvas.create_image(
    287.5,
    699.0,
    image=entry_image_28
)
entry_28 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_28.place(
    x=260.0,
    y=690.0,
    width=55.0,
    height=16.0
)

entry_image_29 = PhotoImage(
    file=relative_to_assets("entry_29.png"))
entry_bg_29 = canvas.create_image(
    287.5,
    741.0,
    image=entry_image_29
)
entry_29 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_29.place(
    x=260.0,
    y=732.0,
    width=55.0,
    height=16.0
)

entry_image_30 = PhotoImage(
    file=relative_to_assets("entry_30.png"))
entry_bg_30 = canvas.create_image(
    287.5,
    720.0,
    image=entry_image_30
)
entry_30 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_30.place(
    x=260.0,
    y=711.0,
    width=55.0,
    height=16.0
)

canvas.create_text(
    361.0,
    670.0,
    anchor="nw",
    text="p_risc",
    fill="#000000",
    font=("Inter", 14 * -1)
)

entry_image_31 = PhotoImage(
    file=relative_to_assets("entry_31.png"))
entry_bg_31 = canvas.create_image(
    380.5,
    699.0,
    image=entry_image_31
)
entry_31 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_31.place(
    x=353.0,
    y=690.0,
    width=55.0,
    height=16.0
)

entry_image_32 = PhotoImage(
    file=relative_to_assets("entry_32.png"))
entry_bg_32 = canvas.create_image(
    380.5,
    741.0,
    image=entry_image_32
)
entry_32 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_32.place(
    x=353.0,
    y=732.0,
    width=55.0,
    height=16.0
)

entry_image_33 = PhotoImage(
    file=relative_to_assets("entry_33.png"))
entry_bg_33 = canvas.create_image(
    380.5,
    720.0,
    image=entry_image_33
)
entry_33 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_33.place(
    x=353.0,
    y=711.0,
    width=55.0,
    height=16.0
)

canvas.create_text(
    435.0,
    670.0,
    anchor="nw",
    text="p_avoid_B",
    fill="#000000",
    font=("Inter", 14 * -1)
)

entry_image_34 = PhotoImage(
    file=relative_to_assets("entry_34.png"))
entry_bg_34 = canvas.create_image(
    462.5,
    699.0,
    image=entry_image_34
)
entry_34 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_34.place(
    x=435.0,
    y=690.0,
    width=55.0,
    height=16.0
)

entry_image_35 = PhotoImage(
    file=relative_to_assets("entry_35.png"))
entry_bg_35 = canvas.create_image(
    462.5,
    741.0,
    image=entry_image_35
)
entry_35 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_35.place(
    x=435.0,
    y=732.0,
    width=55.0,
    height=16.0
)

entry_image_36 = PhotoImage(
    file=relative_to_assets("entry_36.png"))
entry_bg_36 = canvas.create_image(
    462.5,
    720.0,
    image=entry_image_36
)
entry_36 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_36.place(
    x=435.0,
    y=711.0,
    width=55.0,
    height=16.0
)

canvas.create_text(
    43.0,
    350.0,
    anchor="nw",
    text="p_ill1",
    fill="#000000",
    font=("Inter", 14 * -1)
)

entry_image_37 = PhotoImage(
    file=relative_to_assets("entry_37.png"))
entry_bg_37 = canvas.create_image(
    147.5,
    360.0,
    image=entry_image_37
)
entry_37 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_37.place(
    x=120.0,
    y=351.0,
    width=55.0,
    height=16.0
)

canvas.create_text(
    217.0,
    350.0,
    anchor="nw",
    text="p_ill2",
    fill="#000000",
    font=("Inter", 14 * -1)
)

entry_image_38 = PhotoImage(
    file=relative_to_assets("entry_38.png"))
entry_bg_38 = canvas.create_image(
    321.5,
    360.0,
    image=entry_image_38
)
entry_38 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_38.place(
    x=294.0,
    y=351.0,
    width=55.0,
    height=16.0
)

canvas.create_text(
    408.0,
    350.0,
    anchor="nw",
    text="p_ill3",
    fill="#000000",
    font=("Inter", 14 * -1)
)

entry_image_39 = PhotoImage(
    file=relative_to_assets("entry_39.png"))
entry_bg_39 = canvas.create_image(
    512.5,
    360.0,
    image=entry_image_39
)
entry_39 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_39.place(
    x=485.0,
    y=351.0,
    width=55.0,
    height=16.0
)

entry_image_40 = PhotoImage(
    file=relative_to_assets("entry_40.png"))
entry_bg_40 = canvas.create_image(
    283.5,
    274.0,
    image=entry_image_40
)
entry_40 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_40.place(
    x=256.0,
    y=265.0,
    width=55.0,
    height=16.0
)

canvas.create_text(
    47.0,
    444.0,
    anchor="nw",
    text="IQ <",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    266.0,
    443.0,
    anchor="nw",
    text="IQ >",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    204.0,
    444.0,
    anchor="nw",
    text="IQ",
    fill="#000000",
    font=("Inter", 14 * -1)
)

entry_image_41 = PhotoImage(
    file=relative_to_assets("entry_41.png"))
entry_bg_41 = canvas.create_image(
    114.5,
    453.0,
    image=entry_image_41
)
entry_41 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_41.place(
    x=87.0,
    y=444.0,
    width=55.0,
    height=16.0
)

entry_image_42 = PhotoImage(
    file=relative_to_assets("entry_42.png"))
entry_bg_42 = canvas.create_image(
    325.5,
    453.0,
    image=entry_image_42
)
entry_42 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_42.place(
    x=298.0,
    y=444.0,
    width=55.0,
    height=16.0
)

entry_image_43 = PhotoImage(
    file=relative_to_assets("entry_43.png"))
entry_bg_43 = canvas.create_image(
    147.5,
    176.0,
    image=entry_image_43
)
entry_43 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_43.place(
    x=120.0,
    y=167.0,
    width=55.0,
    height=16.0
)

entry_image_44 = PhotoImage(
    file=relative_to_assets("entry_44.png"))
entry_bg_44 = canvas.create_image(
    147.5,
    196.0,
    image=entry_image_44
)
entry_44 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_44.place(
    x=120.0,
    y=187.0,
    width=55.0,
    height=16.0
)

canvas.create_text(
    256.0,
    186.0,
    anchor="nw",
    text="Init_capit IC",
    fill="#000000",
    font=("Inter", 14 * -1)
)

entry_image_45 = PhotoImage(
    file=relative_to_assets("entry_45.png"))
entry_bg_45 = canvas.create_image(
    383.5,
    196.0,
    image=entry_image_45
)
entry_45 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_45.place(
    x=356.0,
    y=187.0,
    width=55.0,
    height=16.0
)

entry_image_46 = PhotoImage(
    file=relative_to_assets("entry_46.png"))
entry_bg_46 = canvas.create_image(
    447.0,
    175.0,
    image=entry_image_46
)
entry_46 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_46.place(
    x=440.0,
    y=168.0,
    width=14.0,
    height=12.0
)

canvas.create_text(
    459.0,
    165.0,
    anchor="nw",
    text="custom_seed",
    fill="#000000",
    font=("Inter", 14 * -1)
)

entry_image_47 = PhotoImage(
    file=relative_to_assets("entry_47.png"))
entry_bg_47 = canvas.create_image(
    447.0,
    152.0,
    image=entry_image_47
)
entry_47 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_47.place(
    x=440.0,
    y=145.0,
    width=14.0,
    height=12.0
)

canvas.create_text(
    459.0,
    142.0,
    anchor="nw",
    text="clock_seed",
    fill="#000000",
    font=("Inter", 14 * -1)
)



read_selection = IntVar()

radiobutton_1 = Radiobutton(window, text="read CA_STATES", variable=read_selection, value=1, highlightthickness=0)
radiobutton_1.place(x=256, y=55)

radiobutton_2 = Radiobutton(window, text="read A_PROFILE", variable=read_selection, value=2, highlightthickness=0)
radiobutton_2.place(x=256, y=73)

radiobutton_3 = Radiobutton(window, text="read RAND_NUM", variable=read_selection, value=3, highlightthickness=0)
radiobutton_3.place(x=256, y=91)


entry_image_51 = PhotoImage(
    file=relative_to_assets("entry_51.png"))
entry_bg_51 = canvas.create_image(
    263.0,
    127.0,
    image=entry_image_51
)
entry_51 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_51.place(
    x=256.0,
    y=120.0,
    width=14.0,
    height=12.0
)

canvas.create_text(
    275.0,
    117.0,
    anchor="nw",
    text="test 1",
    fill="#000000",
    font=("Inter", 14 * -1)
)

entry_image_52 = PhotoImage(
    file=relative_to_assets("entry_52.png"))
entry_bg_52 = canvas.create_image(
    263.0,
    163.0,
    image=entry_image_52
)
entry_52 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_52.place(
    x=256.0,
    y=156.0,
    width=14.0,
    height=12.0
)

canvas.create_text(
    275.0,
    153.0,
    anchor="nw",
    text="test3",
    fill="#000000",
    font=("Inter", 14 * -1)
)

entry_image_53 = PhotoImage(
    file=relative_to_assets("entry_53.png"))
entry_bg_53 = canvas.create_image(
    263.0,
    145.0,
    image=entry_image_53
)
entry_53 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_53.place(
    x=256.0,
    y=138.0,
    width=14.0,
    height=12.0
)

canvas.create_text(
    275.0,
    135.0,
    anchor="nw",
    text="test 2",
    fill="#000000",
    font=("Inter", 14 * -1)
)

# entry_image_54 = PhotoImage(
#     file=relative_to_assets("entry_54.png"))
# entry_bg_54 = canvas.create_image(
#     263.0,
#     39.0,
#     image=entry_image_54
# )
# entry_54 = Entry(
#     bd=0,
#     bg="#D9D9D9",
#     fg="#000716",
#     highlightthickness=0
# )
# entry_54.place(
#     x=256.0,
#     y=32.0,
#     width=14.0,
#     height=12.0
# )
debug = IntVar()
# checkbox_54 = Checkbutton(window, variable=debug, bd=0, bg="white", activebackground="white", fg="#000716", highlightthickness=0)
# checkbox_54.place(x=256.0, y=32.0)

C2 = Checkbutton(window, text = "Debug", variable = debug,
   onvalue = 1, offvalue = 0, height=0,
   width = 5)
C2.place(x=256.0, y=32.0)

# canvas.create_text(
#     275.0,
#     29.0,
#     anchor="nw",
#     text="debug",
#     fill="#000000",
#     font=("Inter", 14 * -1)
# )

entry_image_55 = PhotoImage(
    file=relative_to_assets("entry_55.png"))
entry_bg_55 = canvas.create_image(
    492.5,
    196.0,
    image=entry_image_55
)
entry_55 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_55.place(
    x=440.0,
    y=187.0,
    width=105.0,
    height=16.0
)

entry_image_56 = PhotoImage(
    file=relative_to_assets("entry_56.png"))
entry_bg_56 = canvas.create_image(
    147.5,
    98.0,
    image=entry_image_56
)
entry_56 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_56.place(
    x=120.0,
    y=89.0,
    width=55.0,
    height=16.0
)

entry_image_57 = PhotoImage(
    file=relative_to_assets("entry_57.png"))
entry_bg_57 = canvas.create_image(
    147.5,
    118.0,
    image=entry_image_57
)
entry_57 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_57.place(
    x=120.0,
    y=109.0,
    width=55.0,
    height=16.0
)

entry_image_58 = PhotoImage(
    file=relative_to_assets("entry_58.png"))
entry_bg_58 = canvas.create_image(
    147.5,
    138.0,
    image=entry_image_58
)
entry_58 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_58.place(
    x=120.0,
    y=129.0,
    width=55.0,
    height=16.0
)

entry_image_59 = PhotoImage(
    file=relative_to_assets("entry_59.png"))
entry_bg_59 = canvas.create_image(
    147.5,
    60.0,
    image=entry_image_59
)
entry_59 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_59.place(
    x=120.0,
    y=50.0,
    width=55.0,
    height=18.0
)

canvas.create_rectangle(
    9.989501953125,
    243.0,
    593.989501953125,
    244.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    10.0,
    647.0,
    594.0,
    648.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    613.0,
    818.9999999999999,
    1179.0,
    820.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    613.0,
    544.9999999999999,
    1179.0,
    546.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    612.754150390625,
    543.9989013671875,
    613.754150390625,
    820.0001831054688,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    1177.24169921875,
    543.9998168945312,
    1178.24169921875,
    819.0002746582031,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    10.0,
    754.0,
    594.0,
    755.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    593.0,
    242.0,
    594.0,
    648.0111083984375,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    593.0,
    647.0,
    594.0,
    755.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    10.0,
    242.0,
    11.0,
    648.0111083984375,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    10.0,
    647.0,
    11.0,
    755.0,
    fill="#000000",
    outline="")




display_button = Button(window, text="Wyświetl wartości", command=print_entries)
display_button.place(x=450, y=800)
window.resizable(False, False)
window.mainloop()
